### ISSUE TITLE
replace local storage usage by redux toolkit

### ISSUE THREAD

**Issue by OBeeNya** [OBeeNya/42_ft_transcendence#36]

**Comment by felixbarriere** [comment]
Cons of LocalStorage: XSS.
Apres quelques recherches, s'il y a une faille XSS, l'attaquant peut avoir acces au token qu'il soit dans le LS ou dans un cookie.
Pour notre cas, je n'ai pas reussi à simuler d'attaque XSS, j'ai l'impression qu'on est ok.

exemples: 
<a href="#" onclick="alert(JSON.stringify(localStorage))">click me</a>;
<img src onerror="alert('hey')">;

Si vraiment on veut changer de stratégie, solutions:
- hasher le token (et le dehasher à chaque utilisation, comme les mdp dans la DB).
- Redux? (semble aussi vulnérable que le [reste](https://security.stackexchange.com/questions/160324/is-redux-a-secure-place-to-store-jwt-tokens#:~:text=Redux%20stores%20the%20state%20in,take%20care%20of%20XSS%20properly.)
-

**Comment by OBeeNya** [comment]
On ne peut pas "dé-hasher" qch. Mais on peut décrypter qch qui a été encrypté, par ex. via module 'crypto'. Je pensais le faire éventuellement pour la clé tfa dans la bdd.

**Comment by felixbarriere** [comment]
Pourquoi React protege des attaques XSS:
https://www.stackhawk.com/blog/react-xss-guide-examples-and-prevention/


Solution "idéale" (trop compliqué vu l'avancée du projet):
stocker "en dur" dans le code (comme essayé au debut), et utiliser un refreshToken pour remettre à jour à chaque changement de page.
https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#basics-login
